IF (FFTW3_ROOT)
    # force re-find programs
    set(FFTW3_LIBRARY NOTFOUND CACHE FILE "" FORCE)
    set(FFTW3_INCLUDE_DIR NOTFOUND CACHE PATH "" FORCE)
ENDIF (FFTW3_ROOT) 

FIND_LIBRARY(FFTW3_LIBRARY fftw3 HINTS ${FFTW3_ROOT} PATH_SUFFIXES "lib")
find_path(FFTW3_INCLUDE_DIR NAMES fftw3.h HINTS ${FFTW3_ROOT} PATH_SUFFIXES "include")

IF (FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)
   SET(FFTW3_FOUND TRUE)
ENDIF (FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)

IF (FFTW3_FOUND)
   IF (NOT FFTW3_FIND_QUIETLY)
      MESSAGE(STATUS "Found FFTW3: ${FFTW3_LIBRARY}")
   ENDIF (NOT FFTW3_FIND_QUIETLY)
ELSE (FFTW3_FOUND)
   IF (FFTW3_FIND_REQUIRED)
      MESSAGE(STATUS "Could not find FFTW3")
   ENDIF (FFTW3_FIND_REQUIRED)
ENDIF (FFTW3_FOUND)
