IF (ARGTABLE2_ROOT)
    # force re-find programs
    set(ARGTABLE2_LIBRARY NOTFOUND CACHE FILE "" FORCE)
    set(ARGTABLE2_INCLUDE_DIR NOTFOUND CACHE PATH "" FORCE)
ENDIF (ARGTABLE2_ROOT)

FIND_LIBRARY(ARGTABLE2_LIBRARY argtable2 HINTS ${ARGTABLE2_ROOT} PATH_SUFFIXES "lib") 
FIND_PATH(ARGTABLE2_INCLUDE_DIR argtable2.h HINTS ${ARGTABLE2_ROOT} PATH_SUFFIXES "include")

IF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)
   SET(ARGTABLE2_FOUND TRUE)
ENDIF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)


IF (ARGTABLE2_FOUND)
   IF (NOT ARGTABLE2_FIND_QUIETLY)
      MESSAGE(STATUS "Found Argtable2: ${ARGTABLE2_LIBRARY}")
   ENDIF (NOT ARGTABLE2_FIND_QUIETLY)
ELSE (ARGTABLE2_FOUND)
   IF (ARGTABLE2_FIND_REQUIRED)
      MESSAGE(WARNING "Could not find Argtable2")
   ENDIF (ARGTABLE2_FIND_REQUIRED)
ENDIF (ARGTABLE2_FOUND)
