FIND_PATH(MATLAB_ROOT "extern/include/mex.h" DOC "Path to your Matlab installation root (where to find bin/ and extern/include/ dirs)")

IF (MATLAB_ROOT)
    # force re-find programs and includes
    set(MATLAB_MEX_COMPILER NOTFOUND CACHE FILE "doc" FORCE) 
    set(MATLAB_MEXEXT NOTFOUND CACHE FILE "doc" FORCE)
    set(MATLAB_INCLUDE_DIR NOTFOUND CACHE PATH "doc" FORCE)
    FIND_PROGRAM(MATLAB_MEX_COMPILER mex HINTS ${MATLAB_ROOT} PATH_SUFFIXES "bin")
    FIND_PROGRAM(MATLAB_MEXEXT mexext HINTS ${MATLAB_ROOT} PATH_SUFFIXES "bin")
    FIND_PATH(MATLAB_INCLUDE_DIR "mex.h" ${MATLAB_ROOT}/extern/include)
ENDIF (MATLAB_ROOT)

IF(MATLAB_MEXEXT)
    execute_process(COMMAND ${MATLAB_MEXEXT} OUTPUT_VARIABLE MATLAB_MEX_EXTENSION)
	IF(MATLAB_MEX_EXTENSION)
		string(STRIP ${MATLAB_MEX_EXTENSION} MATLAB_MEX_EXTENSION)
	ENDIF(MATLAB_MEX_EXTENSION)
ENDIF(MATLAB_MEXEXT)

IF(MATLAB_INCLUDE_DIR AND MATLAB_MEX_COMPILER AND MATLAB_MEX_EXTENSION)
  SET(MATLAB_FOUND TRUE)
ELSE(MATLAB_INCLUDE_DIR AND MATLAB_MEX_COMPILER AND MATLAB_MEX_EXTENSION)
  SET(MATLAB_FOUND FALSE)
ENDIF(MATLAB_INCLUDE_DIR AND MATLAB_MEX_COMPILER AND MATLAB_MEX_EXTENSION)

mark_as_advanced(FORCE MATLAB_MEX_COMPILER MATLAB_MEXEXT MATLAB_INCLUDE_DIR MATLAB_INCLUDE_DIR MATLAB_MEX_EXTENSION)

