IF (SNDFILE_ROOT)
    # force re-find programs
    set(SNDFILE_LIBRARY NOTFOUND CACHE FILE "" FORCE)
    set(SNDFILE_INCLUDE_DIR CACHE PATH "" FORCE)
ENDIF (SNDFILE_ROOT)

FIND_LIBRARY(SNDFILE_LIBRARY sndfile HINTS ${SNDFILE_ROOT} PATH_SUFFIXES "lib") 
find_path(SNDFILE_INCLUDE_DIR NAMES sndfile.h HINTS ${SNDFILE_ROOT} PATH_SUFFIXES "include")

IF (SNDFILE_INCLUDE_DIR AND SNDFILE_LIBRARY)
   SET(SNDFILE_FOUND TRUE)
ENDIF (SNDFILE_INCLUDE_DIR AND SNDFILE_LIBRARY)


IF (SNDFILE_FOUND)
   IF (NOT SNDFILE_FIND_QUIETLY)
      MESSAGE(STATUS "Found libsndfile: ${SNDFILE_LIBRARY}")
   ENDIF (NOT SNDFILE_FIND_QUIETLY)
ELSE (SNDFILE_FOUND)
   IF (SNDFILE_FIND_REQUIRED)
      MESSAGE(WARNING "Could not find libsndfile")
   ENDIF (SNDFILE_FIND_REQUIRED)
ENDIF (SNDFILE_FOUND)
